# This is a config for E2B sandbox template.
# You can use template ID (vs6aqudbgksizknmhzh5) or template name (codeNebula) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codeNebula") # Sync sandbox
# sandbox = await AsyncSandbox.create("codeNebula") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codeNebula')

team_id = "f16a6f41-af5e-4445-a864-89c6b37138d0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codeNebula"
template_id = "vs6aqudbgksizknmhzh5"
